import { readFile, readdir, stat } from "node:fs/promises";
import path from "node:path";

/**
 * Phase 0, step 5 (AI-contribution stance) and step 8 (CLA / heavy legal
 * process): find the files a human would read and pull out the lines
 * that mention AI tooling or a CLA/DCO.
 *
 * This is deliberately a finder, not a judge. Whether a hit amounts to a
 * ban, a disclosure requirement, or nothing at all is a reading judgment
 * the agent makes and cites; Mendophyte only guarantees the lines were
 * actually looked at and that files which exist are not missed.
 */

export type PolicyFileRole = "contributing" | "pr-template" | "agent-instructions" | "legal" | "workflow";

export interface PolicyHit {
  line: number;
  text: string;
}

export interface PolicyFile {
  /** Path relative to the repo root, forward slashes. */
  path: string;
  role: PolicyFileRole;
  bytes: number;
  /** Lines mentioning AI / LLM / assistant tooling. */
  aiHits: PolicyHit[];
  /** Lines mentioning CLA / DCO / sign-off. */
  legalHits: PolicyHit[];
  /** True when the file was too large to scan fully; hits come from the first MAX_SCAN_BYTES. */
  truncated: boolean;
}

export interface PolicyReport {
  files: PolicyFile[];
  /** Candidate locations that were checked and not found, so "no AGENTS.md" is an observation. */
  checked: string[];
}

export const MAX_SCAN_BYTES = 256 * 1024;
export const MAX_HITS_PER_FILE = 15;

// Case-sensitive acronyms first (so "AI" doesn't match "ai" inside words), then the rest case-insensitively.
const AI_ACRONYM = /\b(AI|LLM|LLMs|GPT|GPT-\d|A\.I\.)\b/;
const AI_WORDS =
  /\b(large language model|machine[- ]generated|AI[- ](generated|assisted|written|authored|tool|tools|tooling|usage|disclosure|policy|content|contributions?)|generated (by|with|using) (an? )?(AI|LLM|model|assistant)|copilot|chatgpt|openai|anthropic|claude|gemini|codex|cursor|aider|windsurf|coding assistant|code assistant|artificial intelligence|autogenerated code)\b/i;
const LEGAL_ACRONYM = /\b(CLA|DCO)\b/;
const LEGAL_WORDS =
  /\b(contributor licen[cs]e agreement|developer certificate of origin|signed-off-by|sign[- ]?off|cla-assistant|contributor-assistant|copyright assignment|licen[cs]e agreement)\b/i;

export function findHits(text: string): { ai: PolicyHit[]; legal: PolicyHit[] } {
  const ai: PolicyHit[] = [];
  const legal: PolicyHit[] = [];
  const lines = text.split(/\r?\n/);
  for (let i = 0; i < lines.length; i++) {
    const raw = lines[i];
    if (!raw.trim()) continue;
    const t = raw.trim().slice(0, 240);
    if (ai.length < MAX_HITS_PER_FILE && (AI_ACRONYM.test(raw) || AI_WORDS.test(raw))) ai.push({ line: i + 1, text: t });
    if (legal.length < MAX_HITS_PER_FILE && (LEGAL_ACRONYM.test(raw) || LEGAL_WORDS.test(raw))) legal.push({ line: i + 1, text: t });
  }
  return { ai, legal };
}

interface Candidate {
  rel: string;
  role: PolicyFileRole;
}

/** Fixed-path candidates (matched case-insensitively against what actually exists). */
const FIXED_CANDIDATES: Candidate[] = [
  { rel: "CONTRIBUTING.md", role: "contributing" },
  { rel: "CONTRIBUTING.rst", role: "contributing" },
  { rel: "CONTRIBUTING.txt", role: "contributing" },
  { rel: "CONTRIBUTING", role: "contributing" },
  { rel: ".github/CONTRIBUTING.md", role: "contributing" },
  { rel: "docs/CONTRIBUTING.md", role: "contributing" },
  { rel: "docs/contributing.md", role: "contributing" },
  { rel: "PULL_REQUEST_TEMPLATE.md", role: "pr-template" },
  { rel: ".github/PULL_REQUEST_TEMPLATE.md", role: "pr-template" },
  { rel: ".github/pull_request_template.md", role: "pr-template" },
  { rel: "docs/PULL_REQUEST_TEMPLATE.md", role: "pr-template" },
  { rel: "docs/pull_request_template.md", role: "pr-template" },
  { rel: ".gitlab/merge_request_templates/Default.md", role: "pr-template" },
  { rel: "AGENTS.md", role: "agent-instructions" },
  { rel: "CLAUDE.md", role: "agent-instructions" },
  { rel: ".claude/CLAUDE.md", role: "agent-instructions" },
  { rel: "GEMINI.md", role: "agent-instructions" },
  { rel: ".cursorrules", role: "agent-instructions" },
  { rel: ".windsurfrules", role: "agent-instructions" },
  { rel: ".clinerules", role: "agent-instructions" },
  { rel: "CONVENTIONS.md", role: "agent-instructions" },
  { rel: ".github/copilot-instructions.md", role: "agent-instructions" },
  { rel: "CLA.md", role: "legal" },
  { rel: "CLA.txt", role: "legal" },
  { rel: "CLA", role: "legal" },
  { rel: "DCO", role: "legal" },
  { rel: "DCO.md", role: "legal" },
  { rel: "DCO.txt", role: "legal" },
  { rel: ".clabot", role: "legal" },
  { rel: ".github/CLA.md", role: "legal" },
  { rel: "CONTRIBUTOR_LICENSE_AGREEMENT.md", role: "legal" },
];

/** Directories whose files are all candidates (templates and agent rules). */
const DIR_CANDIDATES: { dir: string; role: PolicyFileRole; filter?: RegExp }[] = [
  { dir: ".github/PULL_REQUEST_TEMPLATE", role: "pr-template" },
  { dir: ".gitlab/merge_request_templates", role: "pr-template" },
  { dir: ".cursor/rules", role: "agent-instructions" },
  { dir: ".github/workflows", role: "workflow", filter: /(cla|dco|contributor|license|licence|sign)/i },
];

async function listDirCaseInsensitive(dir: string): Promise<Map<string, string>> {
  // lowercase name -> actual name
  try {
    const names = await readdir(dir);
    return new Map(names.map((n) => [n.toLowerCase(), n]));
  } catch {
    return new Map();
  }
}

/** Resolves `rel` inside `root` ignoring case on every segment; returns the actual relative path or null. */
async function resolveCaseInsensitive(root: string, rel: string): Promise<string | null> {
  const parts = rel.split("/");
  let cur = root;
  const actual: string[] = [];
  for (const p of parts) {
    const listing = await listDirCaseInsensitive(cur);
    const hit = listing.get(p.toLowerCase());
    if (!hit) return null;
    actual.push(hit);
    cur = path.join(cur, hit);
  }
  return actual.join("/");
}

async function scanFile(root: string, rel: string, role: PolicyFileRole): Promise<PolicyFile | null> {
  const abs = path.join(root, rel);
  let st;
  try {
    st = await stat(abs);
  } catch {
    return null;
  }
  if (!st.isFile()) return null;
  let text = "";
  let truncated = false;
  try {
    const buf = await readFile(abs);
    truncated = buf.length > MAX_SCAN_BYTES;
    text = (truncated ? buf.subarray(0, MAX_SCAN_BYTES) : buf).toString("utf8");
  } catch {
    return null;
  }
  const { ai, legal } = findHits(text);
  return { path: rel, role, bytes: st.size, aiHits: ai, legalHits: legal, truncated };
}

export async function scanPolicyFiles(repoDir: string): Promise<PolicyReport> {
  const files: PolicyFile[] = [];
  const checked: string[] = [];
  const seen = new Set<string>();

  for (const c of FIXED_CANDIDATES) {
    checked.push(c.rel);
    const actual = await resolveCaseInsensitive(repoDir, c.rel);
    if (!actual || seen.has(actual)) continue;
    seen.add(actual);
    const f = await scanFile(repoDir, actual, c.role);
    if (f) files.push(f);
  }

  for (const d of DIR_CANDIDATES) {
    checked.push(d.dir + "/");
    const actualDir = await resolveCaseInsensitive(repoDir, d.dir);
    if (!actualDir) continue;
    let names: string[] = [];
    try {
      names = await readdir(path.join(repoDir, actualDir));
    } catch {
      continue;
    }
    for (const n of names.sort()) {
      if (d.filter && !d.filter.test(n)) continue;
      const rel = `${actualDir}/${n}`;
      if (seen.has(rel)) continue;
      seen.add(rel);
      const f = await scanFile(repoDir, rel, d.role);
      if (f) files.push(f);
    }
  }

  return { files, checked };
}
